[versions]
agp = "8.2.0"
kotlin = "1.9.21"

detekt = "1.23.4"
diktat = "1.2.5"
spotless = "6.22.0"
kotlinpoet = "1.15.2"
junit5 = "5.10.1"
kotlin-compile-testing-fork = "0.4.0"
kotest = "5.8.0"

[libraries]
agp-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
agp-plugin-api = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit5" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
junit-jupiter-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core" }
kotest-bom = { group = "io.kotest", name = "kotest-bom", version.ref = "kotest" }
kotest-property = { group = "io.kotest", name = "kotest-property" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5" }
kotlin-compile-testing = { group = "dev.zacsweers.kctfork", name = "core", version.ref = "kotlin-compile-testing-fork" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.21" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
