name: publish

on:
  workflow_dispatch:

env:
  CI: true
  TERM: dumb
  GRADLE_OPTS: >-
    -Dorg.gradle.dependency.verification.console=verbose

jobs:
  publish:
    name: Assemble, publish
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate

      - name: Assemble, run tests, publish
        env:
          YANDEX_S3_ACCESS_KEY_ID: ${{ secrets.YANDEX_S3_ACCESS_KEY_ID }}
          YANDEX_S3_SECRET_ACCESS_KEY: ${{ secrets.YANDEX_S3_SECRET_ACCESS_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: FCF62075
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: >
          ./gradlew build publishAllPublicationsToPixnewsS3Repository --stacktrace

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: build-outputs
          path: '**/build/outputs'
