name: publish

on:
  workflow_dispatch:

env:
  CI: true
  TERM: dumb
  GRADLE_OPTS: >-
    -Dorg.gradle.dependency.verification.console=verbose

jobs:
  publish:
    name: Assemble, publish to Gradle Plugin Portal
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          dependency-graph: generate

      - name: Assemble, run tests, publish
        env:
          CI: true
          TERM: dumb
          GRADLE_OPTS: >-
            -Dorg.gradle.jvmargs="-Xmx1G -XX:MaxMetaspaceSize=768M -XX:SoftRefLRUPolicyMSPerMB=10 -XX:+UseParallelGC"
            -Dorg.gradle.workers.max=2
            -Dorg.gradle.parallel=false
            -Dorg.gradle.dependency.verification.console=verbose
          KOTLIN_DAEMON_JVMARGS: >-
            -Xmx512M -XX:MaxMetaspaceSize=320M -XX:SoftRefLRUPolicyMSPerMB=10 -XX:+UseParallelGC -XX:NewRatio=1
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          ORG_GRADLE_PROJECT_enableSigning: true
          ORG_GRADLE_PROJECT_signingKeyId: FCF62075
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

        run: >
          ./gradlew
          -Pgradle.publish.key="${{ secrets.GRADLE_PUBLISH_KEY }}"
          -Pgradle.publish.secret="${{ secrets.GRADLE_PUBLISH_SECRET }}"
          build publishPlugins --stacktrace

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: build-outputs
          path: '**/build/outputs'
